packages:
  - packages/*
  - packages-private/*

catalog:
  '@babel/parser': ^7.28.5
  '@babel/types': ^7.28.5
  'estree-walker': ^2.0.2
  'magic-string': ^0.30.21
  'source-map-js': ^1.2.1
  'vite': npm:@voidzero-dev/vite-plus-core@0.0.0-c10c45a293020f462d7f4eee20f9dc761e44fe53
  '@vitejs/plugin-vue': ^6.0.3
  vitest: npm:@voidzero-dev/vite-plus-test@0.0.0-c10c45a293020f462d7f4eee20f9dc761e44fe53
  '@voidzero-dev/vite-plus': 0.0.0-c10c45a293020f462d7f4eee20f9dc761e44fe53

onlyBuiltDependencies:
  - '@swc/core'
  - esbuild
  - puppeteer
  - simple-git-hooks
  - unrs-resolver

peerDependencyRules:
  allowedVersions:
    'typescript-eslint>eslint': '^9.0.0'
    '@typescript-eslint/eslint-plugin>eslint': '^9.0.0'
    '@typescript-eslint/parser>eslint': '^9.0.0'
    '@typescript-eslint/type-utils>eslint': '^9.0.0'
    '@typescript-eslint/utils>eslint': '^9.0.0'
    vite: '*'
    vitest: '*'
  allowAny:
    - vite
    - vitest
overrides:
  vite: 'catalog:'
  vitest: 'catalog:'
