packages:
  - 'packages/*'
  - 'packages-private/*'

catalog:
  '@babel/parser': ^7.29.7
  '@babel/types': ^7.29.7
  'entities': '^7.0.1'
  'estree-walker': ^2.0.2
  'vite': 'https://pkg.pr.new/voidzero-dev/vite-plus/@voidzero-dev/vite-plus-core@1856'
  '@vitejs/plugin-vue': ^6.0.7
  'magic-string': ^0.30.21
  'source-map-js': ^1.2.1

allowBuilds:
  '@parcel/watcher': true
  '@swc/core': true
  'esbuild': true
  'puppeteer': true
  'simple-git-hooks': true
  'unrs-resolver': true
  'vue-demi': true

dedupePeers: true

peerDependencyRules:
  allowedVersions:
    'typescript-eslint>eslint': '^9.0.0'
    '@typescript-eslint/eslint-plugin>eslint': '^9.0.0'
    '@typescript-eslint/parser>eslint': '^9.0.0'
    '@typescript-eslint/type-utils>eslint': '^9.0.0'
    '@typescript-eslint/utils>eslint': '^9.0.0'

overrides:
  vite: 'https://pkg.pr.new/voidzero-dev/vite-plus/@voidzero-dev/vite-plus-core@1856'
  vitest: '4.1.9'

minimumReleaseAge: 60
minimumReleaseAgeExclude:
  - '@voidzero-dev/*'
  - vite-plus
  - '@vitest/*'
  - vite
  - vitest
  - '@oxc-project/*'
  - '@oxlint/*'
  - oxlint
  - oxfmt
  - oxlint-tsgolint

blockExoticSubdeps: false
